#pragma once

#define TERRAR_VALIDATION_LAYER_TOTAL 1
const char *TERRAR_VALIDATION_LAYERS[TERRAR_VALIDATION_LAYER_TOTAL];

#define TERRAR_DEVICE_EXTENSION_TOTAL 1
const char *TERRAR_DEVICE_EXTENSIONS[TERRAR_DEVICE_EXTENSION_TOTAL];
